services:
  # --- Base de Datos Compartida ---
  mysql-db:
    image: mysql:8.0
    container_name: mysql-farmacia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # --- Microservicio Catálogo ---
  ms-catalogo:
    build: ./ms-catalogo
    container_name: ms-catalogo
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_NAME=db_catalogo
      - DB_USER=root
      - DB_PASSWORD=admin
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped

  # --- Microservicio Inventario ---
  ms-inventario:
    build: ./ms-inventario
    container_name: ms-inventario
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_NAME=db_inventario
      - DB_USER=root
      - DB_PASSWORD=admin
      - CATALOGO_URL=http://ms-catalogo:8081/api/medicamentos
    depends_on:
      mysql-db:
        condition: service_healthy
      ms-catalogo:
        condition: service_started
    restart: unless-stopped

  # --- Microservicio Ventas ---
  ms-ventas:
    build: ./ms-ventas
    container_name: ms-ventas
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_NAME=db_ventas
      - DB_USER=root
      - DB_PASSWORD=admin
      - CATALOGO_URL=http://ms-catalogo:8081/api/medicamentos
      - INVENTARIO_URL=http://ms-inventario:8082/api/inventarios
    depends_on:
      mysql-db:
        condition: service_healthy
      ms-catalogo:
        condition: service_started
      ms-inventario:
        condition: service_started
    restart: unless-stopped

  ms-gateway:
    build: ./gateway  # Asegúrate de que la carpeta se llame "gateway"
    container_name: ms-gateway
    ports:
      - "8080:8080"
    depends_on:
      ms-catalogo:
        condition: service_started
      ms-inventario:
        condition: service_started
      ms-ventas:
        condition: service_started
    networks:
      - default

  # --- Frontend React Actualizado ---
  ms-frontend:
    build: ./ms-frontend
    container_name: ms-frontend
    ports:
      - "3000:3000"
    environment:
      # Ahora apuntamos SOLO al Gateway en el puerto 8080
      - VITE_API_BASE_URL=http://localhost:8080
      - NODE_ENV=production
    depends_on:
      - ms-gateway
    restart: unless-stopped

volumes:
  mysql_data: